### ISSUE TITLE
ctrl+t doesn't work in fzf

### ISSUE THREAD

**Issue by zachliu** [coreyja/dotfiles#9]
when using a customized sink function
https://github.com/coreyja/dotfiles/blob/eae27a68b12c097ba9b46179efef8272f9dac565/.vimrc#L183

the default `fzf_action` is not valid anymore. so `ctrl-t` doesn't open the selected file in a new tab :crying_cat_face:

**Comment by coreyja** [comment]
Hey @zachliu, ya the custom sink definitely doesn't have all the options that the standard one does.

I personally haven't used most of the `ctrl` based actions in fzf (though maybe I should lol).
BUT! In the original issue that I contributed to, there have been some people that seem to have gotten it working by taking the default sink and modifying it!
From a quick glance this is the most recent comment that I think has what you are looking for! https://github.com/ryanoasis/vim-devicons/issues/106#issuecomment-451463335
Hopefully that is helpful!

I've been meaning to package this all up into a vim plugin, but haven't gotten around to it yet. Someday!

**Comment by coreyja** [comment]
Also, If you wanted to take a stab at adding that sink approach to my dotfiles I'd welcome a PR :smile:

**Comment by zachliu** [comment]
Yes, my solution was more or less the same as https://github.com/ryanoasis/vim-devicons/issues/106#issuecomment-451463335

It's pretty cool, i mean, using `ctrl-t` and tabs :laughing:

**Comment by coreyja** [comment]
@zachliu I made a separate vim plugin to handle this for me now, so as such I'm moving this issue over there!

https://github.com/coreyja/fzf.devicon.vim/issues/3

Thanks again for making the issue, and I actually thought I had these working in the plugin, so I'll try to take a look soon!

**Comment by coreyja** [comment]
I was actually able to close the issue over in that repo to by fixing the issue! So if you wanted you could use that vim plugin and it should work for you now!
